# Generated by Django 4.1 on 2022-09-05 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_total_point_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
