# Generated by Django 4.1 on 2022-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="total_point",
            field=models.IntegerField(default=0),
        ),
    ]
