# Generated by Django 4.1 on 2022-09-14 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
