# Generated by Django 4.1b1 on 2022-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="scientific_name",
            field=models.CharField(max_length=200, unique=True, verbose_name="학명"),
        ),
    ]
