# Generated by Django 4.1a1 on 2022-06-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name": "Family", "verbose_name_plural": "과"},
        ),
        migrations.AlterModelOptions(
            name="genus",
            options={"verbose_name": "Genus", "verbose_name_plural": "속"},
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"verbose_name": "Species", "verbose_name_plural": "종"},
        ),
        migrations.AddField(
            model_name="family",
            name="name_kor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="과국명"
            ),
        ),
        migrations.AddField(
            model_name="genus",
            name="name_kor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="속국명"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="name_kor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="종국명"
            ),
        ),
    ]
