# Generated by Django 4.1a1 on 2022-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_alter_family_options_alter_genus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="학명"),
        ),
        migrations.AlterField(
            model_name="species",
            name="name_kor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="국명"
            ),
        ),
    ]
