# Generated by Django 4.1b1 on 2022-06-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_alter_species_scientific_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="pid",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="국립수목원도감번호"
            ),
        ),
    ]
