# Generated by Django 4.1a1 on 2022-06-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0003_alter_species_name_alter_species_name_kor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="species",
            old_name="name",
            new_name="scientific_name",
        ),
        migrations.AlterField(
            model_name="genus",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="taxonomy.family",
                verbose_name="과",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="genus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="taxonomy.genus",
                verbose_name="속",
            ),
        ),
    ]
