# Generated by Django 4.1b1 on 2022-07-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0004_alter_family_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="pid2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
