# Generated by Django 4.1b1 on 2022-07-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0005_species_pid2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="pid",
        ),
    ]
