# Generated by Django 4.1b1 on 2022-07-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0006_remove_species_pid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="species",
            old_name="pid2",
            new_name="pid",
        ),
    ]
