# Generated by Django 4.1b1 on 2022-07-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0007_rename_pid2_species_pid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genus",
            options={
                "ordering": ["name_kor"],
                "verbose_name": "Genus",
                "verbose_name_plural": "속",
            },
        ),
    ]
