# Generated by Django 4.1b1 on 2022-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="part",
            field=models.IntegerField(
                choices=[
                    (0, "Unidentified"),
                    (1, "Flower"),
                    (2, "Leaf"),
                    (3, "Fruit"),
                    (4, "Bark"),
                    (5, "Whole"),
                    (9, "Not A Plant"),
                ],
                default=0,
            ),
        ),
    ]
