# Generated by Django 4.1 on 2022-08-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="photos",
            field=models.ManyToManyField(related_name="quizzes", to="photos.photo"),
        ),
    ]
